# Generated by Django 5.1.3 on 2024-12-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(blank=True, default=None, max_length=600, null=True),
        ),
    ]
