# Generated by Django 5.1.4 on 2024-12-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_Image_url',
            field=models.CharField(blank=True, default=None, max_length=600, null=True),
        ),
    ]
