# Generated by Django 5.1.4 on 2025-02-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_Image_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wallet_address',
        ),
    ]
