[phases.setup]
nixPkgs = ["python313", "nodejs_20"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "cd ui && npm install"
]

[phases.build]
cmds = [
  "cd ui && npm run build",
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn server.wsgi:application --bind 0.0.0.0:$PORT"